# Generated by Django 4.2.3 on 2023-08-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
